### ISSUE TITLE
Current "latest" tag failing and incorrect version

### ISSUE THREAD

**Issue by chrisvander** [ignittion/pkl-cli#3]
The "latest" tag is pointing at 0.25.3, which is not the latest version. It is also failing with the following error:
```
0.068 Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/bin/pkl)
0.070 Error relocating /usr/local/bin/pkl: _Znam: symbol not found
0.070 Error relocating /usr/local/bin/pkl: _ZdaPv: symbol not found
```

Switching the tag to 0.26.0 gets it working again.

**Comment by chrisvander** [comment]
On a sidenote, would you like to move this repository into the `pkl-community` organization? It would fit really nicely alongside the repositories there.

**Comment by jesscarlos** [comment]
> On a sidenote, would you like to move this repository into the `pkl-community` organization? It would fit really nicely alongside the repositories there.

Yes, that would be great! Let me know if you're still interested moving it over.

**Comment by jesscarlos** [comment]
> The "latest" tag is pointing at 0.25.3, which is not the latest version. It is also failing with the following error:
> 
> ```
> 0.068 Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/bin/pkl)
> 0.070 Error relocating /usr/local/bin/pkl: _Znam: symbol not found
> 0.070 Error relocating /usr/local/bin/pkl: _ZdaPv: symbol not found
> ```
> 
> Switching the tag to 0.26.0 gets it working again.

Sorry it took so long, fixing it now.
